# Generated by Django 5.2.1 on 2025-07-02 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_inpfile_delete_jibbersichstuffi_node_inpfile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipeName', models.CharField(max_length=200)),
                ('inpFile', models.ManyToManyField(to='polls.inpfile')),
                ('nodes', models.ManyToManyField(to='polls.node')),
            ],
        ),
    ]
