# Generated by Django 5.2.1 on 2025-07-02 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_pipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensorName', models.CharField(max_length=200)),
                ('sensorXCoord', models.FloatField()),
                ('sensorYCoord', models.FloatField()),
                ('inpFile', models.ManyToManyField(to='polls.inpfile')),
                ('sensorNode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.node')),
            ],
        ),
    ]
