# Generated by Django 5.2.1 on 2025-07-02 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_sensor'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeName', models.CharField(max_length=100)),
            ],
        ),
    ]
