# Generated by Django 5.2.1 on 2025-07-02 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_pipe_pipetype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pipe',
            name='pipeType',
        ),
    ]
