# Generated by Django 5.2.1 on 2025-07-02 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_remove_pipe_pipetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipe',
            name='pipeType',
            field=models.ForeignKey(default='pipe', on_delete=django.db.models.deletion.CASCADE, to='polls.pipetype'),
        ),
    ]
