# Generated by Django 4.2.23 on 2025-07-22 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InpFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('x_coordinate', models.FloatField()),
                ('y_coordinate', models.FloatField()),
                ('has_sensor', models.BooleanField()),
                ('inp_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iole.inpfile')),
            ],
        ),
        migrations.CreateModel(
            name='Pipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('from_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upstream_pipe_set', to='iole.node')),
                ('inp_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iole.inpfile')),
                ('to_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downstream_pipe_set', to='iole.node')),
            ],
        ),
    ]
