# Generated by Django 5.2.1 on 2025-07-17 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nodeName', models.CharField(max_length=10)),
                ('nodeXCoord', models.FloatField()),
                ('nodeYCoord', models.FloatField()),
                ('inpFile', models.ManyToManyField(to='interface.inpfile')),
            ],
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='PipeType',
        ),
        migrations.AddField(
            model_name='pipe',
            name='fromNode',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pipe',
            name='toNode',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensor',
            name='sensorNode',
            field=models.ManyToManyField(blank=True, to='interface.node'),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
