name: django test using manage.py test

on: [push]

jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setting up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      -  run: python -m pip install --upgrade pip
      -  run: pip install -r src/requirements.txt
      -  run: python ./src/manage.py test
